#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export PATH=/home/rahman/.npm-packages/bin:$PATH
# export PATH=/home/rahman/.pyenv/versions/3.9.11/bin:$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH

export GOPATH=$HOME/go
export PATH="$PATH:$GOPATH/bin"
# export GOPATH="$GOPATH:/home/rahman/Documents/courses/go/go-lib"

export PATH=$HOME/.fnm:$PATH
export PATH="$PATH:./node_modules/.bin"
eval "$(fnm env)"
eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"

# pnpm
export PNPM_HOME="/home/rahman/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end

export FLYCTL_INSTALL="/home/rahman/.fly"
  export PATH="$FLYCTL_INSTALL/bin:$PATH"

  export DENO_INSTALL="/home/rahman/.deno"
  export PATH="$DENO_INSTALL/bin:$PATH"
export PATH="$HOME/.emacs.d/bin:$PATH"

# cargo
. "/home/rahman/.local/share/cargo/env"

# npm
PATH="$HOME/.local/bin:$PATH"
export npm_config_prefix="$HOME/.local"
